apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-api
  namespace: cats-dogs

spec:
  type: NodePort

  selector:
    app: cats-dogs-api

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500